// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtwtdnjkwsvidzramjyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0d3Rkbmprd3N2aWR6cmFtanl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2ODM2NjQsImV4cCI6MjA1NTI1OTY2NH0.fiVo9oDxBJqLahLRPeznmF4VtFHJNpVJ8v0m8HenHmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);